// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.7
// source: colodigits.proto

package colodigits

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ColodigitID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ColodigitID) Reset() {
	*x = ColodigitID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_colodigits_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColodigitID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColodigitID) ProtoMessage() {}

func (x *ColodigitID) ProtoReflect() protoreflect.Message {
	mi := &file_colodigits_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColodigitID.ProtoReflect.Descriptor instead.
func (*ColodigitID) Descriptor() ([]byte, []int) {
	return file_colodigits_proto_rawDescGZIP(), []int{0}
}

func (x *ColodigitID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Colodigit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    *ColodigitID `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Digit int32        `protobuf:"varint,2,opt,name=digit,proto3" json:"digit,omitempty"`
	R     []byte       `protobuf:"bytes,3,opt,name=r,proto3" json:"r,omitempty"`
	G     []byte       `protobuf:"bytes,4,opt,name=g,proto3" json:"g,omitempty"`
	B     []byte       `protobuf:"bytes,5,opt,name=b,proto3" json:"b,omitempty"`
}

func (x *Colodigit) Reset() {
	*x = Colodigit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_colodigits_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Colodigit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Colodigit) ProtoMessage() {}

func (x *Colodigit) ProtoReflect() protoreflect.Message {
	mi := &file_colodigits_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Colodigit.ProtoReflect.Descriptor instead.
func (*Colodigit) Descriptor() ([]byte, []int) {
	return file_colodigits_proto_rawDescGZIP(), []int{1}
}

func (x *Colodigit) GetId() *ColodigitID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Colodigit) GetDigit() int32 {
	if x != nil {
		return x.Digit
	}
	return 0
}

func (x *Colodigit) GetR() []byte {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *Colodigit) GetG() []byte {
	if x != nil {
		return x.G
	}
	return nil
}

func (x *Colodigit) GetB() []byte {
	if x != nil {
		return x.B
	}
	return nil
}

type NoParamIO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NoParamIO) Reset() {
	*x = NoParamIO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_colodigits_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoParamIO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoParamIO) ProtoMessage() {}

func (x *NoParamIO) ProtoReflect() protoreflect.Message {
	mi := &file_colodigits_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoParamIO.ProtoReflect.Descriptor instead.
func (*NoParamIO) Descriptor() ([]byte, []int) {
	return file_colodigits_proto_rawDescGZIP(), []int{2}
}

var File_colodigits_proto protoreflect.FileDescriptor

var file_colodigits_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x6f, 0x6c, 0x6f, 0x64, 0x69, 0x67, 0x69, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x1d, 0x0a, 0x0b, 0x43, 0x6f, 0x6c, 0x6f, 0x64, 0x69, 0x67, 0x69, 0x74, 0x49,
	0x44, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x75, 0x0a, 0x09, 0x43, 0x6f, 0x6c, 0x6f, 0x64, 0x69, 0x67, 0x69, 0x74, 0x12, 0x21,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x43, 0x6f, 0x6c,
	0x6f, 0x64, 0x69, 0x67, 0x69, 0x74, 0x49, 0x44, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x88, 0x01,
	0x01, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x69, 0x67, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x64, 0x69, 0x67, 0x69, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x01, 0x72, 0x12, 0x0c, 0x0a, 0x01, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x01, 0x67, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01,
	0x62, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x69, 0x64, 0x22, 0x0b, 0x0a, 0x09, 0x4e, 0x6f, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x49, 0x4f, 0x32, 0xbd, 0x01, 0x0a, 0x10, 0x43, 0x6f, 0x6c, 0x6f, 0x64, 0x69,
	0x67, 0x69, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x26, 0x0a, 0x0c, 0x41, 0x64,
	0x64, 0x43, 0x6f, 0x6c, 0x6f, 0x64, 0x69, 0x67, 0x69, 0x74, 0x12, 0x0a, 0x2e, 0x43, 0x6f, 0x6c,
	0x6f, 0x64, 0x69, 0x67, 0x69, 0x74, 0x1a, 0x0a, 0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x64, 0x69, 0x67,
	0x69, 0x74, 0x12, 0x2b, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6c, 0x6f,
	0x64, 0x69, 0x67, 0x69, 0x74, 0x12, 0x0c, 0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x64, 0x69, 0x67, 0x69,
	0x74, 0x49, 0x44, 0x1a, 0x0a, 0x2e, 0x4e, 0x6f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x49, 0x4f, 0x12,
	0x29, 0x0a, 0x0f, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x6c, 0x6f, 0x64, 0x69, 0x67,
	0x69, 0x74, 0x12, 0x0a, 0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x64, 0x69, 0x67, 0x69, 0x74, 0x1a, 0x0a,
	0x2e, 0x4e, 0x6f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x49, 0x4f, 0x12, 0x29, 0x0a, 0x0d, 0x47, 0x65,
	0x74, 0x43, 0x6f, 0x6c, 0x6f, 0x64, 0x69, 0x67, 0x69, 0x74, 0x73, 0x12, 0x0a, 0x2e, 0x4e, 0x6f,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x49, 0x4f, 0x1a, 0x0a, 0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x64, 0x69,
	0x67, 0x69, 0x74, 0x30, 0x01, 0x42, 0x13, 0x5a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f,
	0x63, 0x6f, 0x6c, 0x6f, 0x64, 0x69, 0x67, 0x69, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_colodigits_proto_rawDescOnce sync.Once
	file_colodigits_proto_rawDescData = file_colodigits_proto_rawDesc
)

func file_colodigits_proto_rawDescGZIP() []byte {
	file_colodigits_proto_rawDescOnce.Do(func() {
		file_colodigits_proto_rawDescData = protoimpl.X.CompressGZIP(file_colodigits_proto_rawDescData)
	})
	return file_colodigits_proto_rawDescData
}

var file_colodigits_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_colodigits_proto_goTypes = []interface{}{
	(*ColodigitID)(nil), // 0: ColodigitID
	(*Colodigit)(nil),   // 1: Colodigit
	(*NoParamIO)(nil),   // 2: NoParamIO
}
var file_colodigits_proto_depIdxs = []int32{
	0, // 0: Colodigit.id:type_name -> ColodigitID
	1, // 1: ColodigitService.AddColodigit:input_type -> Colodigit
	0, // 2: ColodigitService.DeleteColodigit:input_type -> ColodigitID
	1, // 3: ColodigitService.ModifyColodigit:input_type -> Colodigit
	2, // 4: ColodigitService.GetColodigits:input_type -> NoParamIO
	1, // 5: ColodigitService.AddColodigit:output_type -> Colodigit
	2, // 6: ColodigitService.DeleteColodigit:output_type -> NoParamIO
	2, // 7: ColodigitService.ModifyColodigit:output_type -> NoParamIO
	1, // 8: ColodigitService.GetColodigits:output_type -> Colodigit
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_colodigits_proto_init() }
func file_colodigits_proto_init() {
	if File_colodigits_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_colodigits_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColodigitID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_colodigits_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Colodigit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_colodigits_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoParamIO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_colodigits_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_colodigits_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_colodigits_proto_goTypes,
		DependencyIndexes: file_colodigits_proto_depIdxs,
		MessageInfos:      file_colodigits_proto_msgTypes,
	}.Build()
	File_colodigits_proto = out.File
	file_colodigits_proto_rawDesc = nil
	file_colodigits_proto_goTypes = nil
	file_colodigits_proto_depIdxs = nil
}
